### ISSUE TITLE
build kernel with o=<outside tree build failes issue 3.0.8

### ISSUE THREAD

**Issue by rodb70** [MIPS/CI20_linux#14]
When trying to build Linux kernel by placing kernel object files outside tree the build fails with following error message:
  CC      drivers/video/jz4780-hdmi/api/api.o
Assembler messages:
Fatal error: can't create drivers/video/jz4780-hdmi/api/api.o: No such file or directory
make[6]: **\* [drivers/video/jz4780-hdmi/api/api.o] Error 2

Command to replicate issue:
make ARCH=mips CROSS_COMPILE=mips-linux-gnu- uImage O=../build/kernel/

Workaround to continue building:
mkdir -p ../build/kernel/drivers/video/jz4780-hdmi/{api,bsp,core,edid,hdcp,phy,test,util}

**Comment by ZubairLK** [comment]
Hi Rod,

Could you try with the following patch

https://groups.google.com/forum/#!topic/mips-creator-ci20-dev/pnsMdUw8WMc

**Comment by rodb70** [comment]
ZubairLK,

Applying that patch means the build works fine thanks.
