### ISSUE TITLE
Highmem causes applications to crash

### ISSUE THREAD

**Issue by pcercuei** [MIPS/CI20_linux#18]
When highmem is enabled on 3.18, userspace applications are very likely to crash with a SIGILL / SIGSEGV / SIGBUS signal.
Disabling highmem in the kernel, or reducing the RAM amount to 256 MiB in u-boot's command line, make those issues disappear.

**Comment by ZubairLK** [comment]
Can you check now after the last three fixes I just pushed? 

Previously, with highmem, rootfs on nand, ci20 boot would crash at init.

Now it boots and looks like running.

**Comment by pcercuei** [comment]
Looks fixed indeed; thanks!
