### ISSUE TITLE
Build failure on JZ4780 generic target

### ISSUE THREAD

**Issue by ChrisPWilson** [MIPS/CI20_linux#2]
Building the generic target results in the error:

DTC     arch/mips/jz4780/dts/generic.dtb
ERROR (duplicate_label): Duplicate label 'extal' on /clocks/oscillator and /clocks/extal
ERROR: Input tree has errors, aborting (use -f to force output)
make[3]: **\* [arch/mips/jz4780/dts/generic.dtb] Error 2
make[2]: **\* [arch/mips/jz4780/dts] Error 2
make[1]: **\* [arch/mips/jz4780] Error 2
make[1]: **\* Waiting for unfinished jobs....

I'm using the IA32 compiler here:

https://sourcery.mentor.com/GNUToolchain/release2791?cmpid=7108

**Comment by paulburton** [comment]
As I mentioned by email, my inclination is to fix this by just removing the generic "board" which I'm not sure gives us very much. Any objections?

**Comment by ZubairLK** [comment]
pretty redundant atm.

generic board can always be added later on if several similar jz4780 based boards prop up..

**Comment by ChrisPWilson** [comment]
I have no objections, other than the fact that a "generic" target might be useful as a reference.
Re. "similar jz4780 boards," we do have an npm801 tablet, support for which would be nice :)

**Comment by paulburton** [comment]
Even then a generic "board" wouldn't be so useful, since essentially all commonality between boards is just due to the SoC & thus already abstracted. Patch submitted.

There are some npm801 tablets in the Leeds office, I'll see if I can nab one at some point :)

**Comment by paulburton** [comment]
Fixed by commit c16c790f953c "MIPS: remove generic jz4780 "board"".
