### ISSUE TITLE
DM9000: sometimes fails to read id.

### ISSUE THREAD

**Issue by Pteridium** [MIPS/CI20_linux#26]
This issue can be solved changing reset-gpios with reset-gpio in ci20.dts or patching dm9000.c.
The first one is the fastest.
A diff can be done easily but, what is the preferred solution?

**Comment by ZubairLK** [comment]
IIRC, device tree convention says it needs to be "reset-gpios".
So wherever it is reset-gpio. It should be "reset-gpios"..

http://www.spinics.net/lists/devicetree/msg62688.html

**Comment by Pteridium** [comment]
My fault: I didn't fixed the dm9000 patch in openwrt.
Sorry.

https://github.com/Pteridium/OpenWRT-CI20/blob/CI20-0.3/target/linux/jzrisc/patches-3.18/401-dm9000-ci20-hack.patch

**Comment by ZubairLK** [comment]
Closing this issue.
