### ISSUE TITLE
Fails to build Octeon kernel

### ISSUE THREAD

**Issue by jcowgill** [MIPS/CI20_linux#3]
I've just tried to rebuild the full Debian kernel with all the different CPU flavours with the CI20 patches applied. The Loongson flavours build fine but the Octeon flavour fails with:

```
arch/mips/built-in.o: In function `jz_wait_irqoff':
idle.c:(.text+0x1d118): undefined reference to `r4k_blast_dcache'
idle.c:(.text+0x1d11c): undefined reference to `r4k_blast_dcache'
/home/jcowgill/linux/linux/Makefile:891: recipe for target 'vmlinux' failed
```

Presumably because `arch/mips/mm/c-r4k.c` where `r4k_blast_dcache` is not included in Octeon builds.

**Comment by ZubairLK** [comment]
Do the ci20 patches break it? Or does mainline 3.16 doesn't build octeon..

You are checking the 3.16 branch right. Not 3.0.8?

**Comment by jcowgill** [comment]
Yes the ci20 patches break it. Caused by this commit: df7fddc1805cbfdff5c01c175429613057921a80

**Comment by ZubairLK** [comment]
In arch/mips/kernel/idle.c , r4k_blast_dcache is added as an extern. I guess that causes it.
Would it be wise to wrap an ifdef around it for jz4780?

https://github.com/MIPS/CI20_linux/commit/df7fddc1805cbfdff5c01c175429613057921a80#diff-41daf0317d230554ab5e59efee6e8311

**Comment by ZubairLK** [comment]
closing this issue. as we upstream this won't happen.
